// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZmJ9vlLQNAu--MOU7yRiq6X__a-hrwok',
    appId: '1:943822923765:web:2ebc6e1e94df357036a2bc',
    messagingSenderId: '943822923765',
    projectId: 'phopesreducer',
    authDomain: 'phopesreducer.firebaseapp.com',
    storageBucket: 'phopesreducer.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaRPB6akqU7QPL8APj08rEN-O-6ufgmSM',
    appId: '1:943822923765:android:2381427142ea9f1536a2bc',
    messagingSenderId: '943822923765',
    projectId: 'phopesreducer',
    storageBucket: 'phopesreducer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyogKsOy1bvQ7E2BoA8G2bXjH5hU11p1c',
    appId: '1:943822923765:ios:304e810061c3ac8f36a2bc',
    messagingSenderId: '943822923765',
    projectId: 'phopesreducer',
    storageBucket: 'phopesreducer.appspot.com',
    iosClientId: '943822923765-q596tfeal4qqrsbdq02jn7hstekn7502.apps.googleusercontent.com',
    iosBundleId: 'com.example.phopesCjw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyogKsOy1bvQ7E2BoA8G2bXjH5hU11p1c',
    appId: '1:943822923765:ios:12e76b0df375b59836a2bc',
    messagingSenderId: '943822923765',
    projectId: 'phopesreducer',
    storageBucket: 'phopesreducer.appspot.com',
    iosClientId: '943822923765-r5qdp4hbsneagfm5a8te7kiucrar3nao.apps.googleusercontent.com',
    iosBundleId: 'com.example.phopesCjw.RunnerTests',
  );
}
